# Generated by Django 4.2.12 on 2024-08-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.AddField(
            model_name='quiz',
            name='no_ques',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=30),
        ),
    ]
