# Generated by Django 4.2.12 on 2024-08-06 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_remove_question_order_quiz_no_ques_quiz_time_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.quiz'),
        ),
    ]
